services:
  postgres:
    container_name: postgres
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  webapp:
    container_name: PersonalBlog
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=${PG_DB_NAME};Username=${PG_USER};Password=${PG_PASSWORD}
      - ASPNETCORE_URLS=http://+:${PORT}
      - Admin__Email=${NET_ADMIN_EMAIL}
      - Admin__Password=${NET_PASSWORD}
      - Serilog__WriteTo__0__Args__uri=http://loki:3100

    depends_on:
      postgres:
        condition: service_healthy
      loki:
        condition: service_healthy
    networks:
      - app_network
      - monitoring

  loki:
      image: grafana/loki:latest
      container_name: loki
      ports:
        - "3100:3100"
      volumes:
        - ./loki-config.yaml:/etc/loki/loki-config.yaml
        - loki-data:/loki
      command: -config.file=/etc/loki/loki-config.yaml
      restart: unless-stopped
      networks:
        - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitoring
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - loki
    restart: unless-stopped


networks:
  app_network:
    driver: bridge
  monitoring:
    driver: bridge

volumes:
  postgres_data:
  grafana-data:
  loki-data:
